In [1]:
import numpy as np

In [2]:
#1 Проверьте, есть ли в данном двумерном массиве нулевой столбец

arr = np.array([[0, 1, 3], [0, 1, 3], [0, 1, 3]])

zero_column = arr.sum(axis=0)
lenght = len(zero_column)

for i in range(lenght):
    if zero_column[i] == 0:
        print("true")
        break
    else:
        print("false")
        break

true


In [3]:
#2 Для данной матрицы сосчитайте среднее значение по строкам и вычтете из каждой строки соответствующее среднее

arr = np.array([[0, 1, 3], [0, 8, 3], [0, 19, 4]], dtype = np.float)

mean_rows= arr.mean(axis = 1)

for i in range(lenght):
    arr[i, 0] -= mean_rows[i]
    
print(arr)

[[-1.33333333  1.          3.        ]
 [-3.66666667  8.          3.        ]
 [-7.66666667 19.          4.        ]]


In [4]:
#3 Для данного двумерного массива верните элементы, большие 6 и делящиеся на 3

arr = np.array([[12, 1, 3], [0, 18, 3], [0, 1, 24]])
arr = arr[arr > 6]
arr = arr[arr % 3 == 0]

print(arr)

# Скажите, пожалуйста, почему arr = arr[arr % 3 == 0 and arr > 6] не работает? 
# Он выявляет ошибку из-за неоднозначного ответа.

[12 18 24]


In [5]:
#4 Поменяйте местами строки матрицы так, чтобы первая строка оказалась последней, вторая – предпоследней и т.д.

arr = np.array([[3, 1, 3], [0, 18, 3], [0, 1, 24],[1, 1, 2]])

sh = int(arr.shape[0] / 2)
arr2 = np.copy(arr[0:sh, :])

for i in range(sh):
    arr[i, :] = arr[i * -1 - 1, :]
    arr[i * -1 - 1, :] = arr2[i, :]
    
print(arr)

# Скажите, пожалуйста, почему на
#
# for i in range(sh):
#    a = arr[i, :]
#    arr[i, :] = arr[i * -1 - 1, :]
#    arr[i * -1 - 1, :] = a
#
# вместо того, чтобы выводить [[ 1  1 24],[ 0  1 24],[ 0 18  3], [ 3  1  3]]
# он выводит [[1, 1, 24], [0, 1, 24], [0, 1, 24],[1, 1, 24]]?

[[ 1  1  2]
 [ 0  1 24]
 [ 0 18  3]
 [ 3  1  3]]


In [6]:
#5 Для данной матрицы верните уникальный набор её ненулевых строк

arr = np.array([[0, 0, 0], [0, 1, 3], [0, 1, 3]])

zero_row = arr.sum(axis=1)
lenght = len(zero_row)

for i in range(lenght):
    if zero_row[i] == 0:
        print(i)

0


In [7]:
#6 Для трёхмерного массива верните диагонали его двумерных компонентов

arr = np.array([[[2, 5], [3, 8]], [[6, 7], [9, 1]]])

diagonals = []
sh = arr.shape[1]

for i in range(sh):
    diagonal = [arr[i][0][0], arr[i][1][1]]
    diagonals.append(diagonal)

print(diagonals)

[[2, 8], [6, 1]]


In [8]:
#7 Переставьте столбцы данной матрицы по заданной перестановке индексов

arr = np.array([[0, 18, 3], [0, 1, 24],[1, 1, 24]])

arr2 = np.copy(arr)
sh = arr.shape[1]

for i in range(sh):
    a = int(input())
    arr[:, i] = arr2[:, a]
    
print(arr)

1
2
0
[[18  3  0]
 [ 1 24  0]
 [ 1 24  1]]
